### ISSUE TITLE
Sistema de Monitoramento - IFSC 

### ISSUE THREAD

**Issue by eduardocorrea62** [sergiopetrovcic/IFSC_PJ326-2023#1]
Dando os primeiros passos nessa plataforma.

**Comment by sergiopetrovcic** [comment]
Olá Eduardo! Testando as funcionalidades? Veja que é possível atribuir _issues_ a usuários, colocar _labels_, entre outras coisas. Este texto pode ser formatado, possuir link, fazer menção (@eduardocorrea62 e @tatidaff), etc.

**Comment by tatidaff** [comment]
Testando...

**Comment by sergiopetrovcic** [comment]
Fechando.
